### ISSUE TITLE
Allow selecting tomato

### ISSUE THREAD

**Issue by dgershman** [bmlt-enabled/bmlt-api-explorer#11]
Because this a dropdown, there isn't a way to select tomato.  We would need a way to select that so folks could write queries.

**Comment by GarrettWeinberg** [comment]
I think i need @jbraswell input on this. the data isnt available here https://tomato.bmltenabled.org/rest/v1/rootservers/
If there is an endpoint for tomato i can hit to get `?switcher=GetFormats` and `?switcher=GetServiceBodies` etc, i just need to know what it is and i can just as easily set that option

**Comment by dgershman** [comment]
you would use https://tomato.bmltenabled.org/main_server

**Comment by GarrettWeinberg** [comment]
thanks. Ill get this added to the dropdown.

**Comment by GarrettWeinberg** [comment]
this is added and has been deployed to gh-pages
