### ISSUE TITLE
Keep the hierarchy structure of service bodies

### ISSUE THREAD

**Issue by dgershman** [bmlt-enabled/bmlt-api-explorer#12]
The visual appearance of the service body hierarchy is very useful for understanding how things are organized.

**Comment by GarrettWeinberg** [comment]
@radius314 This is what im working on now. Im trying to figure out the logic of matching the returned parent_id to the id. Im assuming that ill need to separate it into multiple arrays. so loop through and get all parent_id, then when i map through the full array, match them up. If you have any insight on how to handle this logic, anything would be helpful.

**Comment by GarrettWeinberg** [comment]
I have the structure worked out. Needs to be applied to "included service bodies". Need to do a little cleaning up in the file structure and I also need to work out how to pass the value of the selected service bodies to the main output. Still a work in progress, but def making some progress.

**Comment by GarrettWeinberg** [comment]
This is fixed and working
