### ISSUE TITLE
Have Direct Response URL at the top 

### ISSUE THREAD

**Issue by tempsaint** [bmlt-enabled/bmlt-api-explorer#17]
I suggest either having the Direct Response URL at the top of the page like the old/current Semantic Workshop or somehow make it sticky at the bottom of the viewable screen. Right now the user has to scroll to the bottom to see the URL which is not intuitive.

**Comment by GarrettWeinberg** [comment]
I think this is covered in #7

**Comment by GarrettWeinberg** [comment]
@tempsaint PR #20 fixed this. Let me know what you think.

**Comment by tempsaint** [comment]
Yes, that solution fixes this issue. 
#7 is a different issue.
