### ISSUE TITLE
Footer Tag?

### ISSUE THREAD

**Issue by GarrettWeinberg** [bmlt-enabled/bmlt-api-explorer#19]
@alanborning im hoping to get some insight from you on this. I was considering just removing the footer, but I wanted to defer to you on wether or not we need or want to have some sort of disclaimer/footer tag on this. I dont really see a need for it, but i know you have been doing a bunch of stuff with the licensing and you are much more versed in what we need or not than i am.

**Comment by alanb2718** [comment]
It seems fine to omit it.  I'd suggest having a license in the git repository though .....

**Comment by GarrettWeinberg** [comment]
Thanks @alanborning.
