### ISSUE TITLE
Add README.md or CONTRIBUTE.md on how to run locally and develop locally.

### ISSUE THREAD

**Issue by dgershman** [bmlt-enabled/bmlt-api-explorer#8]
I was able to figure this out on my own, but we would want to reduce the level of effort for someone new to jump in and contribute.

For the record, I ran

```
npm install
npm start
```

**Comment by GarrettWeinberg** [comment]
Yea, ive been meaning to put it together. Will get this put up this week.
npm or yarn, either will work

**Comment by GarrettWeinberg** [comment]
Readme updated
